### ISSUE TITLE
a quick question about download process yolov5 master.zip file to root

### ISSUE THREAD

**Issue by farhanrbnn** [kaylode/vehicle-counting#18]
i really love your repo here, it such a great project. i have a quick question for you. before inference process, there's a process to download file like this.
`Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip`
is it really mandatory to download the file ? or you can put the file locally ? thank you.

**Comment by kaylode** [comment]
Hi @farhanrbnn , thanks for your interest in this project.

For your question

> i really love your repo here, it such a great project. i have a quick question for you. before inference process, there's a process to download file like this. `Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /root/.cache/torch/hub/master.zip` is it really mandatory to download the file ? or you can put the file locally ? thank you.

- No, it's not required to download that file, I suppose that happens because I used `torch.hub.load('ultralytics/yolov5', 'custom')` in the code. Instead you can use a local YOLOv5 repo, according to [this](https://github.com/ultralytics/yolov5/issues/36) (in the "Custom Models" section).  However, you should use the repo in which you used to train the model for compatibility.

**Comment by farhanrbnn** [comment]
thanks for your answer, i just curious if it's can be local or not. keep up the good work mate.
